--- 
- hosts: all
  become: true
  vars: 
    file_path: /usr/local/epam
    package_name: 
     - 'telnet'
     - 'httpd'
     - 'wget'
  tasks:
    - name: Check File path
      stat: 
        path: "{{ file_path }}"
      register: filestatus
    
    - name: Install package on system
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ package_name }}"
      when: filestatus.stat.exists
