- name: Create the EC2 instance
  hosts: localhost
  gather_facts: false
  vars:
    name: myinstance
    ami: ami-07ebfd5b3428b6f4d
    #Other vars ommited for brevity
  tasks:
    - name: Launch Instance
      ec2:
        key_name: 14th-march-2020-dell-garima
        group: WebSG
        instance_type: t2.micro
        image: "{{ ami }}"
        user_data: "{{ lookup('file', 'user_data.sh') }}"
        wait: true
        region: us-east-1
        vpc_subnet_id: subnet-28b5fd4f
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Name: "{{ name }}"
        instance_tags:
          Name: from_ansible
      register: ec2